name: TooGoodToGo scan

on:
  schedule:
    # every 10 minutes 06–18 UTC → 08–20 CEST
    - cron: "*/10 6-18 * * *"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch scanner
        uses: actions/checkout@v4
        with:
          repository: Der-Henning/tgtg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: tgtg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tgtg-scanner
        run: |
          pip install git+file://$(pwd)/tgtg

      - name: Run one scan
        env:
          TGTG_EMAIL:     ${{ secrets.TGTG_EMAIL }}
          TGTG_PASSWORD:  ${{ secrets.TGTG_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:  ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python -m tgtg_scanner --only-once
